services:

  # nginx:
  #   build: ./frontend
  #   ports:
  #     - "8082:443"
  #   depends_on:
  #     - gateway
  #   networks:
  #     - backend

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - gateway
    networks:
      - backend

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    env_file:
      - ./gateway/.env
    depends_on:
      - auth-service
    networks:
      - backend
  
  auth-service:
    build: ./auth-service
    expose:
      - "8081"
    volumes:
      - auth_data:/app/data
    networks:
      - backend
    
  user-management-service:
    build: ./user-managment
    expose:
      - "8082"
    volumes:
      - user_data:/app/data
    networks:
      - backend

  chat-service:
    build: ./chat-service
    expose:
      - "8083"
    volumes:
      - chat_data:/app/data
    networks:
      - backend

  pong-service:
    build: ./server-side-pong
    container_name: trascendence-pong-service
    env_file:
      - ./server-side-pong/.env
    ports:
      - "7000:7000"
    depends_on:
      - ai-opponent
    volumes:
      - pong_data:/app/db
    networks:
      - backend
    
  ai-opponent:
     build: ./ai-opponent
     container_name: trascendence-ai-opponent
     env_file:
        - ./ai-opponent/.env
     ports:
        - "7010:7010"
     networks:
        - backend

  tournament-service:
    build: ./tournament-service
    expose:
      - "8085"
    volumes:
      - tournament_data:/app/data
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge

volumes:
  auth_data:
  user_data:
  chat_data:
  tournament_data:
  pong_data: